"""initial schema

Revision ID: 0cdbedd5e498
Revises: 
Create Date: 2026-09-07 00:36:22.834258
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0cdbedd5e498'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_action'), 'audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_table('practice',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('npi', sa.String(length=10), nullable=False),
    sa.Column('tax_id', sa.String(length=20), nullable=True),
    sa.Column('contact_email', sa.String(length=320), nullable=False),
    sa.Column('baa_signed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('batch',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PARSING', 'REVIEW', 'VERIFYING', 'READY', 'DELIVERED', 'PURGED', 'ERROR', name='batchstatus'), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('report_ready_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('purge_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_practice_id'), 'batch', ['practice_id'], unique=False)
    op.create_index(op.f('ix_batch_purge_at'), 'batch', ['purge_at'], unique=False)
    op.create_index(op.f('ix_batch_status'), 'batch', ['status'], unique=False)
    op.create_table('access_token',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.Enum('UPLOAD', 'REPORT_VIEW', name='tokenscope'), nullable=False),
    sa.Column('practice_id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['practice_id'], ['practice.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_access_token_batch_id'), 'access_token', ['batch_id'], unique=False)
    op.create_index(op.f('ix_access_token_practice_id'), 'access_token', ['practice_id'], unique=False)
    op.create_index(op.f('ix_access_token_token_hash'), 'access_token', ['token_hash'], unique=True)
    op.create_table('appointment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('appt_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('patient_name', sa.String(length=255), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('payer_name', sa.String(length=255), nullable=False),
    sa.Column('subscriber_id', sa.String(length=64), nullable=True),
    sa.Column('subscriber_name', sa.String(length=255), nullable=True),
    sa.Column('subscriber_dob', sa.Date(), nullable=True),
    sa.Column('payer_id', sa.String(length=64), nullable=True),
    sa.Column('group_number', sa.String(length=64), nullable=True),
    sa.Column('parse_confidence', sa.Float(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointment_batch_id'), 'appointment', ['batch_id'], unique=False)
    op.create_table('raw_upload',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('s3_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=127), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raw_upload_batch_id'), 'raw_upload', ['batch_id'], unique=False)
    op.create_table('report',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('batch_id', sa.Uuid(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('pdf_s3_key', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batch.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_batch_id'), 'report', ['batch_id'], unique=True)
    op.create_table('verification',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('appointment_id', sa.Uuid(), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'EDI_270_271', name='sourcekind'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'NEEDS_INFO', 'ACTIVE', 'INACTIVE', 'ERROR', name='verificationstatus'), nullable=False),
    sa.Column('payer', sa.String(length=255), nullable=True),
    sa.Column('plan', sa.String(length=255), nullable=True),
    sa.Column('effective_date', sa.Date(), nullable=True),
    sa.Column('annual_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('remaining_benefit', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deductible_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('deductible_met', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('detailed', sa.JSON(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('verified_by', sa.String(length=255), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_appointment_id'), 'verification', ['appointment_id'], unique=True)
    op.create_index(op.f('ix_verification_status'), 'verification', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_status'), table_name='verification')
    op.drop_index(op.f('ix_verification_appointment_id'), table_name='verification')
    op.drop_table('verification')
    op.drop_index(op.f('ix_report_batch_id'), table_name='report')
    op.drop_table('report')
    op.drop_index(op.f('ix_raw_upload_batch_id'), table_name='raw_upload')
    op.drop_table('raw_upload')
    op.drop_index(op.f('ix_appointment_batch_id'), table_name='appointment')
    op.drop_table('appointment')
    op.drop_index(op.f('ix_access_token_token_hash'), table_name='access_token')
    op.drop_index(op.f('ix_access_token_practice_id'), table_name='access_token')
    op.drop_index(op.f('ix_access_token_batch_id'), table_name='access_token')
    op.drop_table('access_token')
    op.drop_index(op.f('ix_batch_status'), table_name='batch')
    op.drop_index(op.f('ix_batch_purge_at'), table_name='batch')
    op.drop_index(op.f('ix_batch_practice_id'), table_name='batch')
    op.drop_table('batch')
    op.drop_table('practice')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_action'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
