"""appointment identity fields nullable for review staging

Revision ID: 571177d85529
Revises: 0cdbedd5e498
Create Date: 2026-09-07 01:36:58.207164
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '571177d85529'
down_revision: Union[str, None] = '0cdbedd5e498'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'patient_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.alter_column('appointment', 'dob',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('appointment', 'payer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('appointment', 'payer_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('appointment', 'dob',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('appointment', 'patient_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
